### ISSUE TITLE
thanks, bug & sugestion

### ISSUE THREAD

**Issue by bCurious3** [leafo/sightreading.training#73]
Thank you so much for making this program!!! It’s a real game changer for anyone  learning to sight read! It has already helped me so much! I can’t express how grateful I am to you!!!

1) I have run into  a problem though:  the flat notes (as in Bb, Eb etc.) don’t seem to work except in the chord setting. It recognises that it’s the right note but then doesn’t move on.. please help!

2) It would be great if you could make a cord trainer with the Jazz chords (4 notes)  and symbols.

Thank you again so much for your amazing work!!

**Comment by ddTech** [comment]
Hi, 

>> I have run into a problem though: the flat notes (as in Bb, Eb etc.) don’t seem to work except in >> the chord setting. It recognises that it’s the right note but then doesn’t move on.. please help!

this issue has been addressed a few times. I have fixed it for my personal server, but leafo sent a note one or two days ago, that he has also fixed it for the "public" version. I think, You may have to wait just a few more days until he updated the live server.

>> It would be great if you could make a cord trainer with the Jazz chords (4 notes) and symbols.

I'm actually thinking about implementing that in my personal version (or if I ever get the environment set up so that I could work with the git files for the public one as well), as this is what I have to train as well and have difficulties with. 

regards

Frank

**Comment by bCurious3** [comment]
Hi Frank,

Thanks for your response. That sounds promising! Please keep me posted if you do develop the jazz chord trainer! 

Best regards,

Frans

**Comment by ddTech** [comment]
Hi Frans, 

it is in a "would be nice to have" state; nothing more yet, same as the "Arpegio-Trainer". 

But...  maybe it's easily doable with the "play  along" section. I just had a brief look there so far, but via the editor one should be able to "compose" a new song which accidentally is just a sequence of jazz chords :-). Same might be possible with Arpegios. ... I'll have to see, if that makes sense / works.

btw. Frans with "s" ..., is that from the Netherlands ? 

Kind regards

Frank

**Comment by almagestalpha** [comment]
The flat notes still don't work on my computer. Should I be concerned or is the fix just not implemented yet?

Best regards

**Comment by ddTech** [comment]
I think it is not implemented yet. Leafo posted that he had fixed it, but the server still has to be updated.

If You want to start right now and don't want to wait, send me an e-Mail with desired name and password and I'll crreate a profile on my personal version. Then You could play with that one until flats work on leafo's page as well. 

For more info see #71 

regards 

Frank

**Comment by ragout13** [comment]
Hi Frank, thanks for this amazing app
I have the same pb, flat notes issue. Can you create a profile on your personal version with fixed issue ? What's your email ?
Many thanks, best

**Comment by leafo** [comment]
deployed a major update which includes the fix for the enharmonic note matching issue. Flat notes should be detected correctly when in staff mode.

**Comment by leafo** [comment]
> It would be great if you could make a cord trainer with the Jazz chords (4 notes) and symbols.

There is a chord mode that's been there for a while that lets you add 7ths to the chords. It's only going to be the diatonic chords tho, not "jazz chords." 

Example configuration: 

![image](https://user-images.githubusercontent.com/15198/79064591-0b354800-7c5f-11ea-9ee2-4d4cf3af0b40.png)

**Comment by bCurious3** [comment]
> deployed a major update which includes the fix for the enharmonic note matching issue. Flat notes should be detected correctly when in staff mode.

Thank you so much!!! Love this trainer so much!!

**Comment by bCurious3** [comment]
Thank you very much!
Yes that could be great. Although I am actually quite into training the reading as a reflex. Even mechanically without sound and  listening to other music while I do it. 
That way I can increase my speed. As the reading just becomes a reflex,  when I play a proper score I then don't need to concentrate on it and can focuse purly on musical expression.

**Comment by bCurious3** [comment]
> Hi Frans,
> 
> it is in a "would be nice to have" state; nothing more yet, same as the "Arpegio-Trainer".
> 
> But... maybe it's easily doable with the "play along" section. I just had a brief look there so far, but via the editor one should be able to "compose" a new song which accidentally is just a sequence of jazz chords :-). Same might be possible with Arpegios. ... I'll have to see, if that makes sense / works.
> 
> btw. Frans with "s" ..., is that from the Netherlands ?
> 
> Kind regards
> 
> Frank

Thanks Frank! From Belgium but live in Germany. Best Frans

**Comment by 3b33** [comment]
Still can't seem to play G flat, registers F sharp but does not realize it's the same thing.
![image](https://github.com/leafo/sightreading.training/assets/41741558/29344967-9843-4914-b16d-a2329de20727)
